apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: master13
      containers:
      - name: frontend
        image: eunbie/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
