apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # Master 노드에만 배포되도록 하는 어노테이션
    nginx.ingress.kubernetes.io/affinity: |
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
spec:
  ingressClassName: nginx
  rules:
    - host: eunbie.site
      http:
        paths:
          # React 정적 파일 먼저 배치
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
          # API 경로
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: node-backend
                port:
                  number: 8000