version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  fastapi-backend:
    build: ./project/fastapi-backend
    container_name: fastapi-backend
    ports:
      - "3000:3000"
    env_file:
      - ./project/fastapi-backend/.env
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./project/fastapi-backend:/app

  node-backend:
    build: ./project/node-backend
    container_name: node-backend
    ports:
      - "8000:8000"
    depends_on:
      - fastapi-backend
    restart: always
    environment:
      - FASTAPI_URL=http://fastapi-backend:3000/fastapi
    volumes:
      - ./project/node-backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "8080:80"  # EC2 Nginx에서 이 포트로 접근
    depends_on:
      - node-backend
    restart: always

volumes:
  mongo-data:
