# updated-deployment-probe-fix.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      nodeSelector:
        kubernetes.io/hostname: master13
      containers:
      - name: fastapi
        image: eunbie/fastapi-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        
        envFrom:
        - secretRef:
            name: fastapi-secret
        
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
          valueFrom:
            secretKeyRef:
              name: fastapi-secret
              key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
            
        # # ✅ 수정: 존재하는 엔드포인트로 변경
        # livenessProbe:
        #   httpGet:
        #     path: /  # 또는 /docs
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
          
        # readinessProbe:
        #   httpGet:
        #     path: /  # 또는 /docs
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 5